pull_request_rules:
  - name: Automatic merge
    conditions:
      - "-label=Merge: Manual"
      - "label~=^Type:"
    actions:
      queue:
  - name: Missing type
    conditions:
      - "base=main"
      - "-draft"
      - "-closed"
      - "-label~=^Type:"
    actions:
      comment:
        message: "Please add a type label to your PR"


queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: '{{ title }}'
    queue_conditions:
      - check-success = main_ci
      - "-draft"
      - "-closed"
      - "-conflict"

