name: CI

on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  main_ci:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need this because fetch-tags=true and because of a GHA bug: https://github.com/actions/checkout/issues/1471
          fetch-tags: true
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Run build
        run: |
          make build
      - name: Run lint
        run: |
          make FIX=0 lint
      - name: Run test
        run: |
          make test-unit
      - name: Run Doc
        run: |
          make doc
      - name: Run integration tests
        run: |
          make test-integration
      - name: Run git checks
        run: |
          make no-dirty
      - name: Run clean
        run: |
          make clean
      - name: Run git checks (after clean)
        run: |
          make no-dirty
